### ISSUE TITLE
[BUG] Tag in metadata removed after enter

### ISSUE THREAD

**Issue by jjkoehorst** [UtrechtUniversity/yoda-ansible#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When typing in a tag and you hit enter once sometimes twice it will remove the tag entry

### Expected Behavior

A new entry should be created so you can add another tag

### Steps To Reproduce

1. In safari (tested) crate metadata
2. type in a tag value
3. hit enter once, twice...
4. tag disappears

### Environment

```markdown
- Yoda: wur-yoda.irods.surfsara.nl
- Ansible:
- Operating System: 
- Browser: Safari Version 15.5 (17613.2.7.1.8)
```

### Anything else?

![image](https://user-images.githubusercontent.com/4471699/181463541-4a61feb3-64bf-4252-836a-2b4a77c2bd84.png)

and then

![image](https://user-images.githubusercontent.com/4471699/181463580-76061ae9-cbb5-4aca-bf96-1678cc896af0.png)

**Comment by lwesterhof** [comment]
Tracking this issue in our internal bug tracker as ticket YDA-4758.

**Comment by Danny-dK** [comment]
Added info if helpful. This only happens if there is 1 tag available. The enter key seems to be directing itself to the 'bin' icon which deletes the record (same happens by just clicking on the bin icon). When more than 1 tag is present, the enter key switches between different tags without deleting.

**Comment by lwesterhof** [comment]
Thanks for reporting!
