### ISSUE TITLE
[FEATURE] doi versioning

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#140]
#### Is your feature request related to a problem? Please describe.
It is cumbersome not to be able to update my data files after they have been published.

#### Describe the solution you'd like
A doi versioning type system perhaps like:
- dataverse:
One DOI pointing to the latest version https://doi.org/10.34894/2WZ0S9. You can refer to different versions by specifying it in the dataverse URL link, not a resolvable doi.
https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/2WZ0S9&version=2.0
https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/2WZ0S9&version=1.0
https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/2WZ0S9

- zenodo:
https://help.zenodo.org/#versioning
One base doi, all other versions get their own doi.
https://doi.org/10.5281/zenodo.705645
Specific version doi's (see on the right hand side of that page)
https://zenodo.org/record/800648
https://zenodo.org/record/60943

::EDIT::

- Figshare:
https://help.figshare.com/article/can-i-edit-or-delete-my-research-after-it-has-been-made-public
One base doi and versions are appended to the base doi.
https://doi.org/10.6084/m9.figshare.2066037
https://doi.org/10.6084/m9.figshare.2066037.v16
https://doi.org/10.6084/m9.figshare.2066037.v2

#### Describe alternatives you've considered
Alternative right now would be to fully re-publish the new version with a new doi and link the previous and new versions through the metadata. Perhaps the title of the old version should then also be adjusted in the metadata to make it even more clear that a new versions of the data exists. This would mean more administrative work than 1 doi that points to the latest versions while having the other versions still available.

**Comment by stsnel** [comment]
Thank you for the proposal! We plan to gather input from the data managers next week, and expect to be able to provide an update then.

**Comment by nehamoopen** [comment]
+1 to this feature request!

DOI versioning, or any other to way update files after publication, would be very welcome. It would offer more flexibility to researchers/data managers and allow for (meta)data publications throughout the research cycle. Files can be published as and when they are ready to be shared and one won't have to wait until the project is complete.

I've worked with projects where data collection is ongoing, but they are keen to already publish whatever (meta)data is available since they're open for data sharing and reuse during the study. For such projects, I end up recommending DataverseNL because we forsee several updates to files and (meta)data over time. These updates might also be small - not enough to warrant a publication of a whole new datapackage with a whole new data.

**Comment by stsnel** [comment]
The feature request has been approved at the data manager meeting today. We are now tracking it in our internal system as ticket YDA-4822. Next action will be for the Yoda team to schedule a meeting with stakeholders to gather input for functional specs.

**Comment by Danny-dK** [comment]
Just FYI Dataverse is also looking to implement doi versioning and seems to prefer the doi appended with '.versionnumer' (i.e. what FigShare is also doing) as well (my preference also). https://github.com/IQSS/dataverse/issues/4499

**Comment by lwesterhof** [comment]
Support for DOI versions is added in https://github.com/UtrechtUniversity/yoda-ruleset/commit/2b15ff9169aa07a819d1a8e3a3e73938be48019b

Will be released with [v1.9.0](https://utrechtuniversity.github.io/yoda/release-notes/release-1.9.html).
