### ISSUE TITLE
[FEATURE] Set the Yoda logo as SRAM collaboration logo

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#382]
#### Is your feature request related to a problem? Please describe.
Not a very pressing request, more a nice-to-have: all the SRAM Collaborations created by Yoda have the VU logo as Collaboration logo (I'm pretty sure because it defaults to the organization logo). Especially as an SRAM organization administrator it would be preferable to be able to visually identify Yoda-created COs.

#### Describe the solution you'd like
Create the COs with the Yoda logo as CO logo. 

The logo can be set on creation via the API https://sram.surf.nl/apidocs/#/Organisation/post_api_collaborations_v1

#### Describe alternatives you've considered
Change manually or via the API, but automatic is better.

#### Additional context
-

**Comment by lwesterhof** [comment]
FIxed in https://github.com/UtrechtUniversity/yoda/commit/b5ceee89110d1c7fd5008eb14e07a9b72235e5c2 and https://github.com/UtrechtUniversity/yoda-ruleset/commit/6e31692265da4945857e257d3bf460504f0edfbb

Defaults to Yoda logo: https://raw.githubusercontent.com/UtrechtUniversity/yoda/development/docs/graphic_mark/png/UU_Beeldmerk_Yoda_FC_DEF.png
